version: '3.8'
services:
  mysql:
    image: mysql
    restart: alaways
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

  user:
    build:
      context: ./user
    ports:
      - "5001:5000"
    depends_on:
      - mysql

  product:
    build:
      context: ./product
    ports:
      - "5002:5000"
    depends_on:
      - mysql

volumes:
  mysql:
  mysql_data:
